# Generated by Django 5.2.5 on 2025-08-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pid', models.IntegerField()),
                ('cpu_percent', models.FloatField(default=0)),
                ('memory_percent', models.FloatField(default=0)),
                ('exe_path', models.TextField(blank=True, default='')),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('sample_time', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('os', models.CharField(blank=True, default='', max_length=64)),
                ('release', models.CharField(blank=True, default='', max_length=64)),
                ('processor', models.CharField(blank=True, default='', max_length=256)),
                ('physical_cores', models.IntegerField(default=0)),
                ('logical_cores', models.IntegerField(default=0)),
                ('cpu_percent', models.FloatField(default=0)),
                ('total_ram', models.BigIntegerField(default=0)),
                ('collected_at', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
