# Generated by Django 5.2.5 on 2025-08-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='boot_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='cpu_freq_current',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='cpu_freq_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='machine',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
