# Generated by Django 5.2.5 on 2025-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_systeminfo_boot_time_systeminfo_cpu_freq_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='ppid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='available_ram',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='storage_free',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='storage_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='storage_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='used_ram',
            field=models.BigIntegerField(default=0),
        ),
    ]
