# Generated by Django 5.2.5 on 2025-08-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_process_ppid_systeminfo_available_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='create_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='process',
            name='memory_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['hostname'], name='process_pro_hostnam_a84257_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['sample_time'], name='process_pro_sample__3a057b_idx'),
        ),
    ]
